import { Translations } from './ru';

export const en: Translations = {
    // General
    appName: 'TrendPulse',

    // Navigation
    nav: {
        dashboard: 'Dashboard',
        savedIdeas: 'Saved Ideas',
        analytics: 'Analytics',
        settings: 'Settings',
    },

    // Backend status
    status: {
        backendConnected: 'Backend Connected',
        usingMockData: 'Using Mock Data',
    },

    // Dashboard
    dashboard: {
        liveClusters: 'Live Clusters',
        activeClusters: 'Active Clusters',
        refreshData: 'Refresh data from API',
        loadingTrends: 'Loading trends...',
        loadingDataPipeline: 'Loading data from API... Pipeline may still be running.',
        noClustersFound: 'No clusters found. Backend may need data ingestion.',
        failedToConnect: 'Failed to connect to backend. Using mock data.',
        failedToRefresh: 'Failed to refresh data. Please try again.',
        views: 'views',
        mViews: 'M views',
        kViews: 'k views',
        growth: 'Growth',
    },

    // Trend Detail
    trendDetail: {
        totalVolume: 'Total volume across platforms:',
        analyzeWithAI: 'Analyze with AI',
        generateIdeas: 'Generate Content Ideas',
        analyzingSemantics: 'Analyzing cluster semantics...',
        unlockAIInsights: 'Unlock AI Insights',
        unlockDescription: 'Free AI will analyze titles, velocity, and engagement to explain why this is trending.',
        whyTrending: "Why It's Trending",
        winningHooks: 'Winning Hooks',
        audience: 'Audience',
        velocityTrack: 'Velocity Track (7d)',
        topPerformingVideos: 'Top Performing Videos',
        failedToAnalyze: 'Failed to analyze trend. Please try again.',
        failedToGenerate: 'Failed to generate ideas.',
    },

    // Content Ideas
    ideas: {
        tailoredContentIdeas: 'Tailored Content Ideas',
        generatedByAI: 'Generated by AI based on active trend data',
        theHook: 'THE HOOK',
        outline: 'OUTLINE',
        saveIdea: 'Save Idea',
        saved: 'Saved!',
    },

    // Saved Ideas Page
    savedIdeas: {
        title: 'Saved Ideas',
        ideaCount: (count: number) => {
            return `${count} ${count === 1 ? 'idea' : 'ideas'} saved`;
        },
        export: 'Export',
        clearAll: 'Clear All',
        confirmClear: 'Are you sure you want to delete all saved ideas?',
        noSavedIdeas: 'No saved ideas yet',
        noSavedIdeasDescription: 'Save content ideas from the dashboard to access them here',
        fromTrend: 'From:',
        copy: 'Copy',
        copied: 'Copied!',
        deleteIdea: 'Delete idea',
        savedOn: 'Saved',
    },

    // Analytics Page
    analyticsPage: {
        title: 'Analytics Dashboard',
        overview: 'Overview of trending content performance',
        noData: 'No data available',
        noDataDescription: 'Load trend data from the dashboard to see analytics',
        total: 'TOTAL',
        videosTracked: 'Videos Tracked',
        viewsLabel: 'VIEWS',
        totalViews: 'Total Views',
        growthLabel: 'GROWTH',
        avgGrowthRate: 'Avg Growth Rate',
        engagementLabel: 'ENGAGEMENT',
        avgScore: 'Avg Score',
        topGrowingTrends: 'Top Growing Trends',
        mostEngagingTrends: 'Most Engaging Trends',
        categoryBreakdown: 'Category Breakdown',
        trends: (count: number) => {
            return `${count} ${count === 1 ? 'trend' : 'trends'}`;
        },
        trendingUp: 'TRENDING UP',
        stable: 'STABLE',
        slowing: 'SLOWING',
        growthAbove50: 'Growth > 50%',
        growth2050: '20-50% growth',
        growthBelow20: 'Growth < 20%',
        engagement: 'engagement',
        views: 'views',
    },

    // Settings Modal
    settings: {
        title: 'API Settings',
        subtitle: 'Configure YouTube & TikTok API keys',
        apiKeysActive: 'API Keys Active',
        youtubeDataAPI: 'YouTube Data API v3',
        tiktokScraptik: 'TikTok (Scraptik / RapidAPI)',
        builtIn: 'Built-in',
        custom: 'Custom',
        builtInKeysNote: 'App ships with built-in keys. If they expire, enter your own below.',
        runFullPipeline: 'Run Full Pipeline',
        runningPipeline: 'Running Pipeline...',
        pipelineInfo: 'Running pipeline... This may take 2-3 minutes.',
        useYourOwnKeys: 'Use Your Own API Keys',
        overrideNote: 'If the built-in keys have expired or hit their limits, enter your own keys below.',
        youtubeAPILabel: 'YouTube Data API v3 —',
        rapidAPILabel: 'RapidAPI (TikTok Scraptik) —',
        getFreeKey: 'Get free key',
        yourYoutubeKey: 'Your YouTube API key...',
        yourRapidAPIKey: 'Your RapidAPI key...',
        save: 'Save',
        enterYoutubeKey: 'Please enter a YouTube key',
        enterRapidAPIKey: 'Please enter a RapidAPI key',
        failedToConnect: 'Failed to connect to backend. Make sure the server is running.',
        failedToPipeline: 'Failed to run pipeline. Check backend logs.',
        securityNote: '🔒 Custom keys are stored in runtime memory only (cleared on restart).',
        quotaNote: '⚡ YouTube: 10,000 free units/day | TikTok Scraptik: free tier on RapidAPI',
        language: 'Language',
        languageRussian: 'Русский',
        languageEnglish: 'English',
    },

    // Formats
    formats: {
        short: 'Short',
        longForm: 'Long-form',
        carousel: 'Carousel',
    },
};
